"""
Election Intelligence - Professional PDF Report Generator
Generates a comprehensive ward-level election strategy report.
"""

import io
from datetime import datetime
from collections import Counter, defaultdict

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, KeepTogether
)
from reportlab.graphics.shapes import Drawing, Rect, String, Wedge, Line
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics import renderPDF


# ── Color palette ────────────────────────────────────────────────────
C_PRIMARY = colors.HexColor('#f97316')
C_GREEN = colors.HexColor('#22c55e')
C_RED = colors.HexColor('#ef4444')
C_BLUE = colors.HexColor('#3b82f6')
C_YELLOW = colors.HexColor('#eab308')
C_PURPLE = colors.HexColor('#a855f7')
C_DARK = colors.HexColor('#1a1d27')
C_SURFACE = colors.HexColor('#232730')
C_MUTED = colors.HexColor('#6b7280')
C_WHITE = colors.white
C_LIGHT_BG = colors.HexColor('#f8f9fa')
C_BORDER = colors.HexColor('#dee2e6')


def _styles():
    """Create custom paragraph styles."""
    base = getSampleStyleSheet()
    s = {}
    s['title'] = ParagraphStyle('RTitle', parent=base['Title'], fontSize=22, textColor=C_PRIMARY,
                                 spaceAfter=4, alignment=TA_CENTER, fontName='Helvetica-Bold')
    s['subtitle'] = ParagraphStyle('RSub', parent=base['Normal'], fontSize=11, textColor=C_MUTED,
                                    spaceAfter=16, alignment=TA_CENTER)
    s['h1'] = ParagraphStyle('RH1', parent=base['Heading1'], fontSize=16, textColor=C_PRIMARY,
                              spaceBefore=20, spaceAfter=10, fontName='Helvetica-Bold',
                              borderWidth=0, borderColor=C_PRIMARY, borderPadding=0)
    s['h2'] = ParagraphStyle('RH2', parent=base['Heading2'], fontSize=13, textColor=colors.HexColor('#1f2937'),
                              spaceBefore=14, spaceAfter=8, fontName='Helvetica-Bold')
    s['h3'] = ParagraphStyle('RH3', parent=base['Heading3'], fontSize=11, textColor=colors.HexColor('#374151'),
                              spaceBefore=10, spaceAfter=6, fontName='Helvetica-Bold')
    s['body'] = ParagraphStyle('RBody', parent=base['Normal'], fontSize=9.5, textColor=colors.HexColor('#374151'),
                                spaceAfter=6, leading=14)
    s['small'] = ParagraphStyle('RSmall', parent=base['Normal'], fontSize=8, textColor=C_MUTED,
                                 spaceAfter=4, leading=11)
    s['kpi_val'] = ParagraphStyle('RKPI', parent=base['Normal'], fontSize=20, textColor=C_PRIMARY,
                                   alignment=TA_CENTER, fontName='Helvetica-Bold', spaceAfter=2)
    s['kpi_label'] = ParagraphStyle('RKPILbl', parent=base['Normal'], fontSize=8, textColor=C_MUTED,
                                     alignment=TA_CENTER, spaceAfter=0)
    s['verdict_win'] = ParagraphStyle('RWin', parent=base['Normal'], fontSize=14,
                                       textColor=C_GREEN, fontName='Helvetica-Bold', alignment=TA_CENTER)
    s['verdict_lose'] = ParagraphStyle('RLose', parent=base['Normal'], fontSize=14,
                                        textColor=C_RED, fontName='Helvetica-Bold', alignment=TA_CENTER)
    s['confidential'] = ParagraphStyle('RConf', parent=base['Normal'], fontSize=7, textColor=C_RED,
                                        alignment=TA_CENTER, fontName='Helvetica-Bold')
    return s


def _header_footer(canvas, doc):
    """Draw header/footer on each page."""
    canvas.saveState()
    w, h = A4
    # Header line
    canvas.setStrokeColor(C_PRIMARY)
    canvas.setLineWidth(2)
    canvas.line(20 * mm, h - 18 * mm, w - 20 * mm, h - 18 * mm)
    canvas.setFont('Helvetica-Bold', 8)
    canvas.setFillColor(C_PRIMARY)
    canvas.drawString(20 * mm, h - 16 * mm, "ELECTION INTELLIGENCE — CONFIDENTIAL")
    canvas.setFillColor(C_MUTED)
    canvas.setFont('Helvetica', 7)
    canvas.drawRightString(w - 20 * mm, h - 16 * mm, datetime.now().strftime('%d %b %Y'))
    # Footer
    canvas.setStrokeColor(C_BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(20 * mm, 15 * mm, w - 20 * mm, 15 * mm)
    canvas.setFont('Helvetica', 7)
    canvas.setFillColor(C_MUTED)
    canvas.drawString(20 * mm, 10 * mm, "Generated by Election Intelligence Tool")
    canvas.drawRightString(w - 20 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _divider():
    return HRFlowable(width="100%", thickness=0.5, color=C_BORDER, spaceBefore=8, spaceAfter=8)


def _kpi_table(items, styles):
    """Create a row of KPI boxes: [(value, label), ...]"""
    val_cells = [Paragraph(str(v), styles['kpi_val']) for v, _ in items]
    lbl_cells = [Paragraph(l, styles['kpi_label']) for _, l in items]
    t = Table([val_cells, lbl_cells], colWidths=[130 / len(items) * mm] * len(items))
    t.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOX', (0, 0), (-1, -1), 0.5, C_BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, C_BORDER),
        ('TOPPADDING', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 1), (-1, 1), 8),
        ('BACKGROUND', (0, 0), (-1, -1), C_LIGHT_BG),
    ]))
    return t


def _data_table(headers, rows, col_widths=None):
    """Create a professional data table."""
    data = [headers] + rows
    n_cols = len(headers)
    if not col_widths:
        col_widths = [160 / n_cols * mm] * n_cols
    t = Table(data, colWidths=col_widths, repeatRows=1)
    style_cmds = [
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 8.5),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('BACKGROUND', (0, 0), (-1, 0), C_PRIMARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), C_WHITE),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, C_BORDER),
        ('BOX', (0, 0), (-1, -1), 0.5, C_BORDER),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]
    # Alternating row colors
    for i in range(1, len(data)):
        if i % 2 == 0:
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), C_LIGHT_BG))
    t.setStyle(TableStyle(style_cmds))
    return t


def _make_pie_drawing(data_dict, width=220, height=160):
    """Create a pie chart drawing from {label: value} dict."""
    d = Drawing(width, height)
    pie = Pie()
    pie.x = width // 2 - 50
    pie.y = 15
    pie.width = 100
    pie.height = 100
    labels = list(data_dict.keys())
    values = list(data_dict.values())
    pie.data = values
    pie.labels = [f"{l} ({v})" for l, v in zip(labels, values)]
    chart_colors = [C_GREEN, C_RED, C_YELLOW, C_BLUE, C_PURPLE, C_PRIMARY,
                    colors.HexColor('#06b6d4'), colors.HexColor('#84cc16')]
    for i in range(len(values)):
        pie.slices[i].fillColor = chart_colors[i % len(chart_colors)]
        pie.slices[i].strokeWidth = 0.5
        pie.slices[i].strokeColor = C_WHITE
    pie.slices[0].popout = 5
    pie.sideLabels = True
    pie.simpleLabels = False
    pie.slices.fontSize = 7
    pie.slices.labelRadius = 1.3
    d.add(pie)
    return d


def _make_bar_drawing(labels, values, width=400, height=150, bar_color=C_PRIMARY):
    """Create a simple vertical bar chart."""
    d = Drawing(width, height)
    bc = VerticalBarChart()
    bc.x = 50
    bc.y = 25
    bc.height = height - 45
    bc.width = width - 70
    bc.data = [values]
    bc.categoryAxis.categoryNames = labels
    bc.categoryAxis.labels.fontSize = 7
    bc.categoryAxis.labels.angle = 0
    bc.valueAxis.labels.fontSize = 7
    bc.valueAxis.valueMin = 0
    bc.bars[0].fillColor = bar_color
    bc.bars[0].strokeWidth = 0
    bc.barWidth = max(8, min(25, (bc.width - 20) / max(len(labels), 1)))
    d.add(bc)
    return d


def generate_report(voters, metadata):
    """Generate a comprehensive election intelligence PDF report.
    Returns BytesIO containing the PDF.
    """
    from analytics import ElectionAnalytics
    analytics = ElectionAnalytics(voters, metadata)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=25 * mm, bottomMargin=20 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
        title="Election Intelligence Report",
        author="Election Intelligence Tool"
    )
    S = _styles()
    story = []

    # ════════════════════════════════════════════════════════════════
    # COVER PAGE
    # ════════════════════════════════════════════════════════════════
    story.append(Spacer(1, 60 * mm))
    story.append(Paragraph("⚡ ELECTION INTELLIGENCE", S['title']))

    ward_count = metadata.get('_ward_count', 1) or 1
    ward_names = metadata.get('_ward_names', [])
    is_multi = ward_count > 1

    if is_multi:
        story.append(Paragraph("COMPREHENSIVE MULTI-WARD ANALYSIS REPORT", ParagraphStyle(
            'CoverSub', parent=S['subtitle'], fontSize=13, spaceAfter=30)))
    else:
        story.append(Paragraph("COMPREHENSIVE WARD ANALYSIS REPORT", ParagraphStyle(
            'CoverSub', parent=S['subtitle'], fontSize=13, spaceAfter=30)))
    story.append(_divider())

    # Show hierarchy context if available
    h_levels = [('_h_state', 'State'), ('_h_district', 'District'), ('_h_taluka', 'Taluka'),
                ('_h_hobli', 'Hobli'), ('_h_gram_panchayat', 'Gram Panchayat'), ('_h_village', 'Village')]
    for key, label in h_levels:
        val = metadata.get(key, '')
        if val:
            story.append(Paragraph(f"<b>{label}:</b> {val}", ParagraphStyle(
                'CoverHL', parent=S['body'], fontSize=11, alignment=TA_CENTER, spaceAfter=3)))

    ward_name = metadata.get('assembly', 'Ward') or 'Ward'
    part = metadata.get('part_no', '')

    if is_multi:
        story.append(Paragraph(f"<b>Wards Covered:</b> {ward_count}", ParagraphStyle(
            'CoverDetail', parent=S['body'], fontSize=12, alignment=TA_CENTER, spaceAfter=4)))
        if len(ward_names) <= 8:
            names_str = ', '.join(ward_names)
            story.append(Paragraph(f"<i>{names_str}</i>", ParagraphStyle(
                'CoverNames', parent=S['body'], fontSize=9, alignment=TA_CENTER,
                spaceAfter=4, textColor=C_MUTED)))
    else:
        story.append(Paragraph(f"<b>Constituency:</b> {ward_name}", ParagraphStyle(
            'CoverDetail', parent=S['body'], fontSize=12, alignment=TA_CENTER, spaceAfter=4)))
        if part:
            story.append(Paragraph(f"<b>Part / Booth:</b> {part}", ParagraphStyle(
                'CoverDetail2', parent=S['body'], fontSize=12, alignment=TA_CENTER, spaceAfter=4)))

    story.append(Paragraph(f"<b>Total Voters:</b> {len(voters)}", ParagraphStyle(
        'CoverDetail3', parent=S['body'], fontSize=12, alignment=TA_CENTER, spaceAfter=4)))
    story.append(Paragraph(f"<b>Report Date:</b> {datetime.now().strftime('%d %B %Y, %I:%M %p')}", ParagraphStyle(
        'CoverDate', parent=S['body'], fontSize=10, alignment=TA_CENTER, spaceAfter=30)))
    story.append(_divider())
    story.append(Spacer(1, 20 * mm))
    story.append(Paragraph("STRICTLY CONFIDENTIAL — FOR INTERNAL USE ONLY", S['confidential']))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # TABLE OF CONTENTS
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("TABLE OF CONTENTS", S['h1']))
    story.append(Spacer(1, 5 * mm))
    toc_items = [
        "1. Executive Summary",
        "2. Voter Demographics",
        "3. Age & Gender Analysis",
        "4. Community / Caste Arithmetic",
        "5. Family & Household Analysis",
        "6. Booth Strength Assessment",
        "7. Winning Formula",
        "8. Historical Election Analysis",
        "9. Voter Classification & Conversion Funnel",
        "10. Tags & Scheme Beneficiary Coverage",
        "11. 3-Contact Strategy Plan",
        "12. Family Influence Targets",
        "13. Election Day Time Slots",
        "14. Field Operations Plan",
        "15. Data Quality Audit",
        "16. Ground Action Plan — Immediate Tasks",
    ]
    for item in toc_items:
        story.append(Paragraph(item, ParagraphStyle('TOC', parent=S['body'], fontSize=10, spaceAfter=6, leftIndent=15)))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 1. EXECUTIVE SUMMARY
    # ════════════════════════════════════════════════════════════════
    summary = analytics.get_summary()
    story.append(Paragraph("1. EXECUTIVE SUMMARY", S['h1']))
    story.append(_divider())

    story.append(_kpi_table([
        (str(summary['total_voters']), 'Total Voters'),
        (str(summary['male_count']), 'Male'),
        (str(summary['female_count']), 'Female'),
        (str(summary['families']), 'Families'),
    ], S))
    story.append(Spacer(1, 4 * mm))
    story.append(_kpi_table([
        (str(summary['youth_voters']), 'Youth (18-25)'),
        (str(summary['first_time_voters']), 'First-Time'),
        (str(summary['senior_voters']), 'Seniors (60+)'),
        (str(summary['needs_transport']), 'Transport Need'),
    ], S))
    story.append(Spacer(1, 4 * mm))

    avg_age = summary['avg_age'] or 'N/A'
    gr = summary['gender_ratio']
    story.append(Paragraph(
        f"Average age of voters is <b>{avg_age}</b> years. Gender ratio stands at <b>{gr}</b> females per 1000 males. "
        f"<b>{summary['youth_voters']}</b> youth voters (18-25) represent the most volatile demographic — "
        f"first contact is critical. <b>{summary['first_time_voters']}</b> voters will cast their vote for the first time.",
        S['body']))

    # Funnel quick summary
    funnel = analytics.get_conversion_funnel()
    story.append(Spacer(1, 3 * mm))
    story.append(Paragraph("<b>Voter Classification Snapshot:</b>", S['body']))
    story.append(_kpi_table([
        (str(funnel['pakka']), 'Pakka ✓'),
        (str(funnel['swing']), 'Swing ↔'),
        (str(funnel['doubtful']), 'Doubtful ?'),
        (str(funnel['virodhi']), 'Virodhi ✗'),
    ], S))

    # Winning formula quick
    election_history = metadata.get('_election_history', [])
    formula = analytics.get_winning_formula(election_history)
    for booth, f in formula.items():
        story.append(Spacer(1, 3 * mm))
        verdict_style = S['verdict_win'] if f['status'] == 'SAFE' else S['verdict_lose']
        story.append(Paragraph(f"Booth {booth} Status: {f['status']}", verdict_style))
        story.append(Paragraph(
            f"Winning Target: {f['winning_target']} votes | Confirmed Pakka: {f['confirmed_pakka']} | "
            f"Gap: {f['gap_to_win']} | Swing Available: {f['swing_available']}",
            ParagraphStyle('FSnap', parent=S['body'], alignment=TA_CENTER, fontSize=9)))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 2. VOTER DEMOGRAPHICS
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("2. VOTER DEMOGRAPHICS", S['h1']))
    story.append(_divider())

    demo_data = [
        ['Metric', 'Value', 'Metric', 'Value'],
        ['Total Voters', str(summary['total_voters']), 'Avg Age', str(avg_age)],
        ['Male', f"{summary['male_count']} ({summary['male_percent']}%)",
         'Female', f"{summary['female_count']} ({summary['female_percent']}%)"],
        ['Youth (18-25)', str(summary['youth_voters']), 'Seniors (60+)', str(summary['senior_voters'])],
        ['First-Time', str(summary['first_time_voters']), 'Gender Ratio', f"{gr}/1000"],
        ['Families', str(summary['families']), 'Avg Family Size', str(summary['avg_family_size'])],
        ['Transport Need', str(summary['needs_transport']), 'Median Age', str(summary.get('median_age', 'N/A'))],
    ]
    t = Table(demo_data, colWidths=[35 * mm, 45 * mm, 35 * mm, 45 * mm])
    t.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BACKGROUND', (0, 0), (-1, 0), C_PRIMARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), C_WHITE),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (2, 1), (2, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 1), (0, -1), 8),
        ('FONTSIZE', (2, 1), (2, -1), 8),
        ('TEXTCOLOR', (0, 1), (0, -1), C_MUTED),
        ('TEXTCOLOR', (2, 1), (2, -1), C_MUTED),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, C_BORDER),
        ('BOX', (0, 0), (-1, -1), 0.5, C_BORDER),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 5 * mm))

    # ════════════════════════════════════════════════════════════════
    # 3. AGE & GENDER ANALYSIS
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("3. AGE & GENDER ANALYSIS", S['h1']))
    story.append(_divider())

    age_groups = summary['age_groups']
    ag_labels = list(age_groups.keys())
    ag_values = list(age_groups.values())
    story.append(Paragraph("<b>Age Distribution</b>", S['h2']))
    story.append(_make_bar_drawing(ag_labels, ag_values, bar_color=C_BLUE))
    story.append(Spacer(1, 3 * mm))

    # Age group table
    ag_rows = [[grp, str(cnt), f"{round(cnt / max(summary['total_voters'], 1) * 100, 1)}%"]
               for grp, cnt in age_groups.items()]
    story.append(_data_table(['Age Group', 'Count', '% of Total'], ag_rows,
                             col_widths=[50 * mm, 40 * mm, 40 * mm]))
    story.append(Spacer(1, 5 * mm))

    # Gender by age
    gba = analytics.get_gender_by_age()
    story.append(Paragraph("<b>Gender by Age Group</b>", S['h2']))
    gba_rows = [[grp, str(d.get('Male', 0)), str(d.get('Female', 0)), str(d.get('Other', 0))]
                for grp, d in gba.items()]
    story.append(_data_table(['Age Group', 'Male', 'Female', 'Other'], gba_rows,
                             col_widths=[40 * mm, 33 * mm, 33 * mm, 33 * mm]))
    story.append(Spacer(1, 3 * mm))

    # Key insight
    dominant_age = max(age_groups, key=age_groups.get) if age_groups else 'N/A'
    story.append(Paragraph(
        f"<b>Key Insight:</b> The largest voter segment is <b>{dominant_age}</b> age group "
        f"with <b>{age_groups.get(dominant_age, 0)}</b> voters. "
        f"Youth voters need door-to-door engagement. Senior voters need transport assurance.",
        S['body']))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 4. COMMUNITY / CASTE ARITHMETIC
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("4. COMMUNITY / CASTE ARITHMETIC", S['h1']))
    story.append(_divider())

    communities = analytics.get_community_analysis()
    known_comm = [c for c in communities if c['community'] != 'Unknown']
    unknown_count = sum(c['count'] for c in communities if c['community'] == 'Unknown')

    if known_comm:
        pie_data = {c['community']: c['count'] for c in known_comm[:8]}
        if unknown_count:
            pie_data['Unknown'] = unknown_count
        story.append(_make_pie_drawing(pie_data, width=350, height=180))
        story.append(Spacer(1, 3 * mm))

    comm_rows = [[c['community'], str(c['count']), f"{c['percent']}%"] for c in communities[:15]]
    story.append(_data_table(['Community', 'Count', 'Vote Share %'], comm_rows,
                             col_widths=[60 * mm, 40 * mm, 40 * mm]))
    story.append(Spacer(1, 4 * mm))

    # Caste strategy
    caste_strategy = analytics.get_caste_strategy()
    if caste_strategy:
        story.append(Paragraph("<b>Caste Strategy Recommendations</b>", S['h2']))
        cs_rows = [[cs['community'], str(cs['total']), f"{cs.get('percent', 0)}%",
                     cs.get('action', 'ENGAGE')]
                    for cs in caste_strategy[:10]]
        story.append(_data_table(['Community', 'Voters', 'Share', 'Strategy'], cs_rows,
                                 col_widths=[45 * mm, 30 * mm, 30 * mm, 40 * mm]))
    story.append(Spacer(1, 3 * mm))

    # Top surnames
    surnames = analytics.get_surname_analysis()
    if surnames:
        story.append(Paragraph("<b>Top Surnames (Community Indicators)</b>", S['h2']))
        sn_rows = [[s['surname'], str(s['count']), f"{s['percent']}%", s['community']]
                    for s in surnames[:15]]
        story.append(_data_table(['Surname', 'Count', '%', 'Community'], sn_rows,
                                 col_widths=[40 * mm, 30 * mm, 25 * mm, 45 * mm]))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 5. FAMILY & HOUSEHOLD ANALYSIS
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("5. FAMILY & HOUSEHOLD ANALYSIS", S['h1']))
    story.append(_divider())

    family_data = analytics.get_family_analysis()
    story.append(_kpi_table([
        (str(family_data['total_families']), 'Total Families'),
        (str(family_data['avg_size']), 'Avg Family Size'),
        (str(len(family_data['large_families'])), 'Large Families (4+)'),
    ], S))
    story.append(Spacer(1, 4 * mm))

    # Family size distribution
    size_dist = family_data['size_distribution']
    if size_dist:
        sd_rows = [[f"{sz} members", str(cnt)] for sz, cnt in sorted(size_dist.items())]
        story.append(Paragraph("<b>Family Size Distribution</b>", S['h2']))
        story.append(_data_table(['Family Size', 'Count'], sd_rows,
                                 col_widths=[60 * mm, 60 * mm]))
    story.append(Spacer(1, 4 * mm))

    # Large families (top 10)
    if family_data['large_families']:
        story.append(Paragraph("<b>Largest Families — Priority Targets</b>", S['h2']))
        lf_rows = [[f['head'], str(f['size']), f['house_no']]
                    for f in family_data['large_families'][:10]]
        story.append(_data_table(['Family Head', 'Members', 'House No'], lf_rows,
                                 col_widths=[60 * mm, 35 * mm, 50 * mm]))
        story.append(Paragraph(
            "<b>Action:</b> Large families control multiple votes. Target the family head — "
            "one successful conversion = multiple votes gained.", S['body']))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 6. BOOTH STRENGTH ASSESSMENT
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("6. BOOTH STRENGTH ASSESSMENT", S['h1']))
    story.append(_divider())

    booth_strength = analytics.get_booth_strength()
    booth_analysis = analytics.get_booth_analysis()

    for booth, data in booth_strength.items():
        story.append(Paragraph(f"<b>Booth {booth}</b>", S['h2']))
        ba = booth_analysis.get(booth, {})
        story.append(_kpi_table([
            (str(data['total']), 'Total Voters'),
            (f"{data['strength_score']}%", 'Strength Score'),
            (str(data['pakka']), 'Pakka'),
            (str(data['virodhi']), 'Virodhi'),
            (str(data['swing']), 'Swing'),
        ], S))
        story.append(Spacer(1, 3 * mm))
        # Demographics for this booth
        story.append(Paragraph(
            f"Male: {ba.get('male', 0)} | Female: {ba.get('female', 0)} | "
            f"Youth: {ba.get('youth', 0)} | Seniors: {ba.get('senior', 0)} | "
            f"First-Time: {ba.get('first_time', 0)} | "
            f"Avg Age: {ba.get('avg_age', 'N/A')} | Families: {ba.get('family_count', 0)}", S['body']))

        # Top communities in booth
        top_comm = ba.get('top_communities', [])
        if top_comm:
            comm_str = ", ".join([f"{c['name']} ({c['count']})" for c in top_comm[:5]])
            story.append(Paragraph(f"<b>Top Communities:</b> {comm_str}", S['body']))
        story.append(Spacer(1, 4 * mm))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 7. WINNING FORMULA
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("7. WINNING FORMULA", S['h1']))
    story.append(_divider())

    wf_rows = []
    for booth, f in formula.items():
        wf_rows.append([
            booth, str(f['total_voters']), str(f['expected_turnout']),
            str(f['winning_target']), str(f['confirmed_pakka']),
            str(f['gap_to_win']), str(f['swing_available']), f['status']
        ])
    story.append(_data_table(
        ['Booth', 'Total', 'Est. Turnout', 'Win Target', 'Pakka', 'Gap', 'Swing Avail', 'Status'],
        wf_rows, col_widths=[18 * mm, 18 * mm, 22 * mm, 22 * mm, 18 * mm, 15 * mm, 22 * mm, 20 * mm]))
    story.append(Spacer(1, 4 * mm))

    for booth, f in formula.items():
        if f['status'] == 'SAFE':
            story.append(Paragraph(
                f"<b>Booth {booth} — SAFE:</b> Confirmed Pakka exceeds winning target. "
                f"Focus on turnout assurance — ensure every Pakka voter reaches the booth.", S['body']))
        elif f['status'] == 'WINNABLE':
            story.append(Paragraph(
                f"<b>Booth {booth} — WINNABLE:</b> Need to convert <b>{f['gap_to_win']}</b> more voters. "
                f"<b>{f['swing_available']}</b> swing voters available — capture "
                f"<b>{f['swing_needed_percent']}%</b> of them to win.", S['body']))
        else:
            story.append(Paragraph(
                f"<b>Booth {booth} — TOUGH:</b> Large gap of {f['gap_to_win']} votes. "
                f"Need aggressive community outreach + opposition weakening strategy.", S['body']))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 8. HISTORICAL ELECTION ANALYSIS
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("8. HISTORICAL ELECTION ANALYSIS", S['h1']))
    story.append(_divider())

    hist_analysis = ElectionAnalytics.get_historical_analysis(election_history)

    if hist_analysis['has_data']:
        story.append(_kpi_table([
            (str(hist_analysis['total_elections']), 'Elections Recorded'),
            (f"{hist_analysis['avg_turnout'] or '—'}%", 'Avg Historical Turnout'),
            (str(len(hist_analysis['party_summary'])), 'Parties Tracked'),
        ], S))
        story.append(Spacer(1, 4 * mm))

        # Past results table
        story.append(Paragraph("<b>Past Election Results</b>", S['h2']))
        hist_rows = []
        for e in hist_analysis['elections']:
            party_str = ', '.join([f"{p['name']}:{p['votes']}" for p in e['parties'][:4]])
            hist_rows.append([
                str(e['year']), e['election_type'],
                f"{e['turnout_pct']}%" if e['turnout_pct'] else '—',
                e['winner'] or '—', party_str or '—',
            ])
        story.append(_data_table(
            ['Year', 'Type', 'Turnout', 'Winner', 'Party Results'],
            hist_rows, col_widths=[18*mm, 25*mm, 20*mm, 22*mm, 65*mm]))
        story.append(Spacer(1, 4 * mm))

        # Party strength summary
        story.append(Paragraph("<b>Party Strength Summary</b>", S['h2']))
        ps_rows = [[p['party'], str(p['total_votes']), str(p['elections_contested']),
                     str(p['wins']), str(p['avg_votes'])]
                    for p in hist_analysis['party_summary'][:10]]
        story.append(_data_table(
            ['Party', 'Total Votes', 'Elections', 'Wins', 'Avg Votes'],
            ps_rows, col_widths=[30*mm, 28*mm, 25*mm, 20*mm, 28*mm]))
        story.append(Spacer(1, 4 * mm))

        # Turnout note
        if hist_analysis['avg_turnout']:
            story.append(Paragraph(
                f"<b>Note:</b> Historical average turnout of <b>{hist_analysis['avg_turnout']}%</b> "
                f"is used in the Winning Formula calculation instead of the default 65%.", S['body']))
    else:
        story.append(Paragraph(
            "<i>No historical election data recorded. Add past results to improve winning formula accuracy.</i>",
            S['body']))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 8. VOTER CLASSIFICATION & CONVERSION FUNNEL
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("9. VOTER CLASSIFICATION & CONVERSION FUNNEL", S['h1']))
    story.append(_divider())

    story.append(_kpi_table([
        (str(funnel['pakka']), 'Pakka (Confirmed)'),
        (str(funnel['swing']), 'Swing (Convertible)'),
        (str(funnel['doubtful']), 'Doubtful'),
        (str(funnel['virodhi']), 'Virodhi (Opposition)'),
    ], S))
    story.append(Spacer(1, 3 * mm))
    story.append(_kpi_table([
        (str(funnel['unclassified']), 'Unclassified'),
        (str(funnel['classified']), 'Total Classified'),
        (str(funnel['silent_voters']), 'Silent Voters'),
    ], S))
    story.append(Spacer(1, 4 * mm))

    # Classification pie
    cls_pie = {'Pakka': funnel['pakka'], 'Swing': funnel['swing'],
               'Doubtful': funnel['doubtful'], 'Virodhi': funnel['virodhi'],
               'Unclassified': funnel['unclassified']}
    cls_pie = {k: v for k, v in cls_pie.items() if v > 0}
    if cls_pie:
        story.append(_make_pie_drawing(cls_pie, width=350, height=180))
    story.append(Spacer(1, 3 * mm))

    # Swing breakdown
    sb = funnel['swing_breakdown']
    story.append(Paragraph("<b>Swing Voter Contact Progress</b>", S['h2']))
    story.append(_data_table(
        ['Stage', 'Count', 'Action Required'],
        [
            ['No Contact Yet', str(sb['no_contact']), 'URGENT: First contact immediately'],
            ['1 Contact Done', str(sb['1_contact']), 'Schedule 2nd contact within 3 days'],
            ['2 Contacts Done', str(sb['2_contacts']), 'Final push — close the conversion'],
            ['3+ Contacts', str(sb['3plus_contacts']), 'Monitor — high conversion probability'],
        ],
        col_widths=[35 * mm, 25 * mm, 80 * mm]))

    # Booth conversion potential
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("<b>Booth-wise Conversion Potential</b>", S['h2']))
    bp = funnel.get('booth_potential', {})
    bp_rows = [[booth, str(d['total']), str(d['swing']), str(d['doubtful']), str(d['unconverted'])]
               for booth, d in bp.items()]
    if bp_rows:
        story.append(_data_table(
            ['Booth', 'Total', 'Swing', 'Doubtful', 'Unconverted'],
            bp_rows, col_widths=[25 * mm, 25 * mm, 30 * mm, 30 * mm, 30 * mm]))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 9. 3-CONTACT STRATEGY PLAN
    # ════════════════════════════════════════════════════════════════
    # ════════════════════════════════════════════════════════════════
    # 10. TAGS & SCHEME BENEFICIARY COVERAGE
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("10. TAGS & SCHEME BENEFICIARY COVERAGE", S['h1']))
    story.append(_divider())

    tag_data = analytics.get_tag_analysis()
    scheme_data = analytics.get_scheme_coverage()

    story.append(_kpi_table([
        (str(tag_data['tagged_voters']), 'Tagged Voters'),
        (f"{tag_data['tagged_percent']}%", 'Tag Coverage'),
        (str(scheme_data['total_beneficiaries']), 'Scheme Beneficiaries'),
        (str(len(scheme_data['scheme_types'])), 'Scheme Types'),
    ], S))
    story.append(Spacer(1, 4 * mm))

    if tag_data['tags']:
        story.append(Paragraph("<b>Tag Distribution</b>", S['h2']))
        tg_rows = [[t['tag'], str(t['count']), f"{t['percent']}%"] for t in tag_data['tags'][:15]]
        story.append(_data_table(['Tag', 'Count', '% of Voters'], tg_rows,
                                 col_widths=[60*mm, 35*mm, 35*mm]))
        story.append(Spacer(1, 4 * mm))

    # Scheme coverage by community
    if scheme_data['per_community']:
        story.append(Paragraph("<b>Scheme Coverage by Community</b>", S['h2']))
        sc_rows = []
        for comm, d in list(scheme_data['per_community'].items())[:12]:
            schemes = ', '.join(list(d.get('top_schemes', {}).keys())[:3]) or '—'
            sc_rows.append([comm, str(d['total']), str(d['beneficiaries']),
                           f"{d['coverage_pct']}%", schemes])
        story.append(_data_table(
            ['Community', 'Total', 'Beneficiaries', 'Coverage', 'Top Schemes'],
            sc_rows, col_widths=[35*mm, 22*mm, 28*mm, 22*mm, 45*mm]))
    else:
        story.append(Paragraph(
            "<i>No scheme tags assigned yet. Tag voters with scheme names for coverage analysis.</i>",
            S['body']))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 11. 3-CONTACT STRATEGY PLAN
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("11. THREE-CONTACT STRATEGY PLAN", S['h1']))
    story.append(_divider())

    contact_plan = analytics.get_three_contact_plan()
    sc = contact_plan['stage_counts']
    story.append(_kpi_table([
        (str(contact_plan['total_targets']), 'Total Targets'),
        (str(sc['need_1st']), 'Need 1st Contact'),
        (str(sc['need_2nd']), 'Need 2nd Contact'),
        (str(sc['need_3rd']), 'Need 3rd Contact'),
    ], S))
    story.append(Spacer(1, 4 * mm))

    # Top priority targets (top 30)
    story.append(Paragraph("<b>Top Priority Targets (by strategic value)</b>", S['h2']))
    targets = contact_plan.get('targets', [])[:30]
    if targets:
        tgt_rows = [[t['name'], str(t.get('age', '')), t.get('booth', ''), t['classification'],
                      str(t['contact_count']), f"→ {t['next_contact']}", str(t['family_size'])]
                     for t in targets]
        story.append(_data_table(
            ['Name', 'Age', 'Booth', 'Class', 'Contacts', 'Next', 'Family'],
            tgt_rows, col_widths=[35 * mm, 15 * mm, 18 * mm, 22 * mm, 20 * mm, 15 * mm, 18 * mm]))
    story.append(Spacer(1, 3 * mm))
    story.append(Paragraph(
        "<b>Strategy:</b> Contact Swing voters 3 times before election. "
        "1st visit = introduce candidate. 2nd visit = address concerns. 3rd visit = confirm commitment. "
        "Family heads with 4+ members get top priority — one conversion = multiple votes.", S['body']))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 12. FAMILY INFLUENCE TARGETS
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("12. FAMILY INFLUENCE TARGETS", S['h1']))
    story.append(_divider())

    fam_influence = analytics.get_family_influence_map()
    story.append(_kpi_table([
        (str(fam_influence['total_families']), 'Influential Families (3+)'),
        (str(fam_influence['total_potential_votes']), 'Total Potential Votes'),
    ], S))
    story.append(Spacer(1, 4 * mm))

    fam_list = fam_influence.get('families', [])[:20]
    if fam_list:
        story.append(Paragraph("<b>Top Influential Families — Visit Priority List</b>", S['h2']))
        fi_rows = [[f['head_name'], str(f['head_age'] or ''), str(f['size']),
                     f['house_no'], f['head_classification'], str(f['head_contacts'])]
                    for f in fam_list]
        story.append(_data_table(
            ['Family Head', 'Age', 'Members', 'House', 'Status', 'Contacts'],
            fi_rows, col_widths=[35 * mm, 15 * mm, 20 * mm, 30 * mm, 22 * mm, 20 * mm]))
    story.append(Spacer(1, 3 * mm))
    story.append(Paragraph(
        "<b>Action:</b> Each row is one household controlling multiple votes. "
        "Convert the head → entire family follows. Prioritize families where head is Swing/Doubtful.",
        S['body']))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 13. ELECTION DAY TIME SLOTS
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("13. ELECTION DAY TIME SLOTS", S['h1']))
    story.append(_divider())

    slots = analytics.get_election_day_slots()
    slot_data = slots.get('slots', {})
    slot_rows = []
    for slot_key, slot_info in slot_data.items():
        label = slot_key.replace('_', ' ').replace('am', ' AM').replace('pm', ' PM')
        count = slot_info.get('count', 0)
        desc = slot_info.get('description', '')
        slot_rows.append([label, str(count), desc])
    if slot_rows:
        story.append(_data_table(['Time Slot', 'Voters', 'Focus'], slot_rows,
                                 col_widths=[35 * mm, 25 * mm, 85 * mm]))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(
        "<b>7-9 AM:</b> Send Pakka voters first — build queue momentum. "
        "<b>9-12 PM:</b> Transport seniors/disabled. "
        "<b>12-3 PM:</b> Follow-up on remaining Pakka. "
        "<b>3-5 PM:</b> Final push — Swing voters, last-minute door knocking.", S['body']))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 14. FIELD OPERATIONS PLAN
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("14. FIELD OPERATIONS PLAN", S['h1']))
    story.append(_divider())

    # Panna Pramukh
    pp_plan = analytics.get_panna_pramukh_plan()
    story.append(Paragraph("<b>Panna Pramukh Assignments</b>", S['h2']))
    pp_rows = [[booth, str(d['total_voters']), str(d['pages_needed']), str(d['workers_needed'])]
               for booth, d in pp_plan.items()]
    story.append(_data_table(['Booth', 'Voters', 'Pages', 'Workers Needed'], pp_rows,
                             col_widths=[30 * mm, 35 * mm, 30 * mm, 40 * mm]))
    story.append(Spacer(1, 4 * mm))

    # Volunteer needs
    vol = analytics.get_volunteer_requirement()
    story.append(Paragraph("<b>Volunteer Requirement — Election Day</b>", S['h2']))
    vol_rows = [[booth, str(d['booth_agents']), str(d['panna_pramukhs']),
                  str(d['slip_distributors']), str(d['transport_coordinators']),
                  str(d['total_volunteers_needed'])]
                 for booth, d in vol.items()]
    story.append(_data_table(
        ['Booth', 'Agents', 'Panna P.', 'Slip Dist.', 'Transport', 'Total'],
        vol_rows, col_widths=[22 * mm, 20 * mm, 22 * mm, 22 * mm, 25 * mm, 22 * mm]))
    story.append(Spacer(1, 4 * mm))

    # Contact coverage
    coverage = analytics.get_contact_coverage()
    story.append(Paragraph("<b>Contact Coverage Status</b>", S['h2']))
    story.append(_kpi_table([
        (f"{coverage['coverage_percent_1x']}%", '1+ Contact'),
        (f"{coverage['coverage_percent_2x']}%", '2+ Contacts'),
        (f"{coverage['coverage_percent_3x']}%", '3+ Contacts'),
    ], S))
    story.append(Spacer(1, 4 * mm))

    # Slip distribution
    slip = analytics.get_slip_distribution_status()
    story.append(Paragraph(
        f"<b>Voter Slips:</b> {slip['delivered']} delivered out of {slip['total']} "
        f"({slip['percent']}%). <b>{slip['pending']}</b> pending.", S['body']))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 15. DATA QUALITY AUDIT
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("15. DATA QUALITY AUDIT", S['h1']))
    story.append(_divider())

    dq = analytics.get_data_quality()
    score_color = 'green' if dq['data_quality_score'] >= 70 else ('orange' if dq['data_quality_score'] >= 50 else 'red')
    story.append(Paragraph(
        f"<b>Data Quality Score: <font color='{score_color}'>{dq['data_quality_score']}/100</font></b>",
        ParagraphStyle('DQScore', parent=S['body'], fontSize=14, alignment=TA_CENTER)))
    story.append(Spacer(1, 4 * mm))

    dq_rows = [
        ['Total Voters', str(dq['total_voters'])],
        ['Missing Age', str(dq['missing_age'])],
        ['Missing Gender', str(dq['missing_gender'])],
        ['Missing Voter ID', str(dq['missing_voter_id'])],
        ['Underage (<18)', str(dq['underage'])],
        ['Very Old (>100)', str(dq['very_old'])],
        ['Duplicate Groups', str(dq['duplicate_groups'])],
        ['Duplicate Voters', str(dq['duplicate_voters'])],
    ]
    story.append(_data_table(['Check', 'Result'], dq_rows,
                             col_widths=[60 * mm, 50 * mm]))
    story.append(Spacer(1, 4 * mm))
    if dq['duplicate_groups'] > 0:
        story.append(Paragraph(
            f"<b>⚠ Warning:</b> {dq['duplicate_groups']} potential duplicate entries detected. "
            f"Review and clean before election day.", S['body']))
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # 16. GROUND ACTION PLAN — IMMEDIATE TASKS
    # ════════════════════════════════════════════════════════════════
    story.append(Paragraph("16. GROUND ACTION PLAN \u2014 IMMEDIATE TASKS", S['h1']))
    story.append(_divider())

    story.append(Paragraph("<b>Phase 1: Immediate (Next 48 Hours)</b>", S['h2']))
    immediate_tasks = [
        f"Classify all {funnel['unclassified']} unclassified voters — door-to-door survey required",
        f"First contact {sb['no_contact']} swing voters who have ZERO contact",
        f"Assign {sum(d['workers_needed'] for d in pp_plan.values())} Panna Pramukhs across all booths",
        "Distribute voter slips to all Pakka voters",
        "Identify and meet heads of all large families (4+ members)",
    ]
    for i, task in enumerate(immediate_tasks, 1):
        story.append(Paragraph(f"<b>{i}.</b> {task}", S['body']))
    story.append(Spacer(1, 4 * mm))

    story.append(Paragraph("<b>Phase 2: Week 1 (Days 3-7)</b>", S['h2']))
    week1_tasks = [
        f"Complete 2nd contact for {sb['1_contact']} swing voters with 1 contact",
        "Door-to-door community meetings in top 3 communities",
        f"Arrange transport for {summary['needs_transport']} voters needing assistance",
        "Setup booth-level WhatsApp groups for Panna Pramukhs",
        "Hold corner meetings in all areas with Virodhi concentration",
    ]
    for i, task in enumerate(week1_tasks, 1):
        story.append(Paragraph(f"<b>{i}.</b> {task}", S['body']))
    story.append(Spacer(1, 4 * mm))

    story.append(Paragraph("<b>Phase 3: Final Push (Days 8-14)</b>", S['h2']))
    final_tasks = [
        f"3rd contact for remaining {sb['2_contacts']} swing voters",
        "Final door-to-door in all areas — confirm Pakka commitment",
        "Distribute remaining voter slips",
        "Confirm transport arrangements for all seniors/disabled",
        "Brief all booth agents on election day protocol",
    ]
    for i, task in enumerate(final_tasks, 1):
        story.append(Paragraph(f"<b>{i}.</b> {task}", S['body']))
    story.append(Spacer(1, 4 * mm))

    story.append(Paragraph("<b>Phase 4: Election Day</b>", S['h2']))
    eday_tasks = [
        "7 AM: Deploy booth agents, start voter queue management",
        "7-9 AM: Send all Pakka voters to booths",
        "9-12 PM: Transport seniors & disabled voters",
        "12 PM: Status check — compare voted vs pending list",
        "3 PM: Emergency outreach to ALL not-voted Pakka/Swing",
        "4-5 PM: Final blitz — pick up every remaining voter",
    ]
    for i, task in enumerate(eday_tasks, 1):
        story.append(Paragraph(f"<b>{i}.</b> {task}", S['body']))
    story.append(Spacer(1, 6 * mm))

    # Voter list for ground workers
    story.append(PageBreak())
    story.append(Paragraph("APPENDIX: VOTER LIST — FIELD WORKER REFERENCE", S['h1']))
    story.append(_divider())
    story.append(Paragraph(
        "Complete voter list for field workers. Use during door-to-door visits.", S['body']))
    story.append(Spacer(1, 3 * mm))

    # Print all voters in compact table (batches of 40 per page)
    voter_batch = []
    for idx, v in enumerate(voters):
        voter_batch.append([
            str(v.get('sr_no', idx + 1)),
            (v.get('name', '') or '')[:22],
            str(v.get('age', '') or ''),
            (v.get('gender', '') or '')[:1],
            (v.get('house_no', '') or '')[:15],
            (v.get('father_name', '') or '')[:20],
            (v.get('voter_id', '') or '')[:12],
        ])
        if len(voter_batch) >= 40 or idx == len(voters) - 1:
            story.append(_data_table(
                ['#', 'Name', 'Age', 'G', 'House', 'Father/Husband', 'Voter ID'],
                voter_batch,
                col_widths=[10 * mm, 35 * mm, 12 * mm, 8 * mm, 25 * mm, 32 * mm, 28 * mm]))
            story.append(Spacer(1, 2 * mm))
            if idx < len(voters) - 1:
                story.append(PageBreak())
            voter_batch = []

    # ════════════════════════════════════════════════════════════════
    # BUILD PDF
    # ════════════════════════════════════════════════════════════════
    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buf.seek(0)
    return buf
